---
# vim: syntax=yaml

# debug ansible_vars:
#- name: Display all variables/facts known for a host
#  debug:
#    var: hostvars[inventory_hostname]
#  tags: debug_info

#- include: security-limits.yml
- include: sysctl.yml
- include: users-and-groups.yml
- include: fix-dirs.yml
- include: update-system.yml
#- include: java.yml

# TODO enable xdm