---
# vim: ts=2 sw=2 et syntax=yaml

- name: set dns fallbacks
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^(#)?hosts:'
    line: 'hosts: files mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] mdns4 dns'
