---
# vim: ts=2 sw=2 et syntax=yaml

# TODO rewrite for looping "apache2", "cgi", "cli", "fpm"

# --------------------------- APACHE2 -------------------------------

- name: php.ini - apache2 - default settings - PHP {{ php_version_inputvar }}
  ini_file:
    path: '/etc/php/apache2-php{{ php_version_inputvar }}/php.ini'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: "Date", option: "date.timezone", value: '"{{ php_timezone }}"' }
    - { section: "PHP", option: "always_populate_raw_post_data", value: "-1" }    # disabled (deprecated)
    - { section: "PHP", option: "error_log", value: '"{{ php_log_path }}/error.log"' }
    - { section: "PHP", option: "max_execution_time", value: "{{ php_max_execution_time }}" }
    - { section: "PHP", option: "max_input_time", value: "{{ php_max_input_time }}" }
    - { section: "PHP", option: "memory_limit", value: "{{ php_memory_limit }}" }
    - { section: "PHP", option: "post_max_size", value: "{{ php_post_max_size }}" }
    - { section: "PHP", option: "upload_max_filesize", value: "{{ php_upload_max_filesize }}" }
    - { section: "PHP", option: "expose_php", value: "{{ php_expose_php }}" }          # security: do not expose php
    - { section: "PHP", option: "display_errors", value: "{{ php_display_errors }}" }  # security: do not show errors onsite
    - { section: "PHP", option: "display_startup_errors", value: "Off" }               # security: do not show errors onsite
    - { section: "Session", option: "session.use_strict_mode", value: "1" }            # security: prevents session fixation attacks
    - { section: "Session", option: "session.gc_maxlifetime", value: "{{ php_session_maxlifetime }}" }    # max session lifetime
    - { section: "dba", option: "opcache.enable", value: "1" }                         # performance: enable opcache ...
    - { section: "dba", option: "opcache.enable_cli", value: "0" }                     # ... but disable opcache for commandline
    - { section: "dba", option: "opcache.memory_consumption", value: "64" }
    - { section: "dba", option: "opcache.interned_strings_buffer", value: "4" }
    - { section: "dba", option: "opcache.max_accelerated_files", value: "2000" }
    - { section: "dba", option: "opcache.max_wasted_percentage", value: "5" }
    - { section: "dba", option: "opcache.use_cwd", value: "1" }
    - { section: "dba", option: "opcache.validate_timestamps", value: "1" }
    - { section: "dba", option: "opcache.revalidate_freq", value: "2" }
    - { section: "dba", option: "opcache.revalidate_path", value: "0" }
    - { section: "dba", option: "opcache.error_log", value: '"{{ php_log_path }}/opcache.log"' }
    - { section: "dba", option: "opcache.log_verbosity_level", value: "1" }
    - { section: "mail function", option: "mail.log", value: '"{{ php_log_path }}/mail.log"' }

# --------------------------- FPM -------------------------------

- name: php.ini - fpm - default settings - PHP {{ php_version_inputvar }}
  ini_file:
    path: '/etc/php/fpm-php{{ php_version_inputvar }}/php.ini'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: "Date", option: "date.timezone", value: '"{{ php_timezone }}"' }
    - { section: "PHP", option: "always_populate_raw_post_data", value: "-1" }    # disabled (deprecated)
    - { section: "PHP", option: "error_log", value: '"{{ php_log_path }}/error.log"' }
    - { section: "PHP", option: "max_execution_time", value: "{{ php_max_execution_time }}" }
    - { section: "PHP", option: "max_input_time", value: "{{ php_max_input_time }}" }
    - { section: "PHP", option: "memory_limit", value: "{{ php_memory_limit }}" }
    - { section: "PHP", option: "post_max_size", value: "{{ php_post_max_size }}" }
    - { section: "PHP", option: "upload_max_filesize", value: "{{ php_upload_max_filesize }}" }
    - { section: "PHP", option: "expose_php", value: "{{ php_expose_php }}" }          # security: do not expose php
    - { section: "PHP", option: "display_errors", value: "{{ php_display_errors }}" }  # security: do not show errors onsite
    - { section: "PHP", option: "display_startup_errors", value: "Off" }               # security: do not show errors onsite
    - { section: "Session", option: "session.use_strict_mode", value: "1" }            # security: prevents session fixation attacks
    - { section: "Session", option: "session.gc_maxlifetime", value: "{{ php_session_maxlifetime }}" }    # max session lifetime
    - { section: "dba", option: "opcache.enable", value: "1" }                    # performance: enable opcache ...
    - { section: "dba", option: "opcache.enable_cli", value: "0" }                # ... but disable opcache for commandline
    - { section: "dba", option: "opcache.memory_consumption", value: "64" }
    - { section: "dba", option: "opcache.interned_strings_buffer", value: "4" }
    - { section: "dba", option: "opcache.max_accelerated_files", value: "2000" }
    - { section: "dba", option: "opcache.max_wasted_percentage", value: "5" }
    - { section: "dba", option: "opcache.use_cwd", value: "1" }
    - { section: "dba", option: "opcache.validate_timestamps", value: "1" }
    - { section: "dba", option: "opcache.revalidate_freq", value: "2" }
    - { section: "dba", option: "opcache.revalidate_path", value: "0" }
    - { section: "dba", option: "opcache.error_log", value: '"{{ php_log_path }}/opcache.log"' }
    - { section: "dba", option: "opcache.log_verbosity_level", value: "1" }
    - { section: "mail function", option: "mail.log", value: '"{{ php_log_path }}/mail.log"' }

# --------------------------- CGI -------------------------------

- name: php.ini - cgi - default settings - PHP {{ php_version_inputvar }}
  ini_file:
    path: '/etc/php/cgi-php{{ php_version_inputvar }}/php.ini'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: "Date", option: "date.timezone", value: '"{{ php_timezone }}"' }
    - { section: "PHP", option: "always_populate_raw_post_data", value: "-1" }    # disabled (deprecated)
    - { section: "PHP", option: "error_log", value: '"{{ php_log_path }}/error_cgi.log"' }
    - { section: "PHP", option: "max_execution_time", value: "{{ php_max_execution_time }}" }
    - { section: "PHP", option: "max_input_time", value: "{{ php_max_input_time }}" }
    - { section: "PHP", option: "memory_limit", value: "{{ php_memory_limit }}" }
    - { section: "PHP", option: "post_max_size", value: "{{ php_post_max_size }}" }
    - { section: "PHP", option: "upload_max_filesize", value: "{{ php_upload_max_filesize }}" }
    - { section: "PHP", option: "expose_php", value: "{{ php_expose_php }}" }          # security: do not expose php
    - { section: "PHP", option: "display_errors", value: "{{ php_display_errors }}" }  # security: do not show errors onsite
    - { section: "PHP", option: "display_startup_errors", value: "Off" }               # security: do not show errors onsite
    - { section: "Session", option: "session.use_strict_mode", value: "1" }            # security: prevents session fixation attacks
    - { section: "Session", option: "session.gc_maxlifetime", value: "{{ php_session_maxlifetime }}" }    # max session lifetime
    - { section: "dba", option: "opcache.enable", value: "1" }                    # performance: enable opcache ...
    - { section: "dba", option: "opcache.enable_cli", value: "0" }                # ... but disable opcache for commandline
    - { section: "dba", option: "opcache.memory_consumption", value: "64" }
    - { section: "dba", option: "opcache.interned_strings_buffer", value: "4" }
    - { section: "dba", option: "opcache.max_accelerated_files", value: "2000" }
    - { section: "dba", option: "opcache.max_wasted_percentage", value: "5" }
    - { section: "dba", option: "opcache.use_cwd", value: "1" }
    - { section: "dba", option: "opcache.validate_timestamps", value: "1" }
    - { section: "dba", option: "opcache.revalidate_freq", value: "2" }
    - { section: "dba", option: "opcache.revalidate_path", value: "0" }
    - { section: "dba", option: "opcache.error_log", value: '"{{ php_log_path }}/opcache_cgi.log"' }
    - { section: "dba", option: "opcache.log_verbosity_level", value: "1" }
    - { section: "mail function", option: "mail.log", value: '"{{ php_log_path }}/mail_cgi.log"' }

# --------------------------- CLI -------------------------------

- name: php.ini - cli - default settings - PHP {{ php_version_inputvar }}
  ini_file:
    path: '/etc/php/cli-php{{ php_version_inputvar }}/php.ini'
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
  with_items:
    - { section: "Date", option: "date.timezone", value: '"{{ php_timezone }}"' }
    - { section: "PHP", option: "always_populate_raw_post_data", value: "-1" }    # disabled (deprecated)
    - { section: "PHP", option: "error_log", value: '"{{ php_log_path }}/error_cli.log"' }
    - { section: "PHP", option: "max_execution_time", value: "{{ php_max_execution_time }}" }
    - { section: "PHP", option: "max_input_time", value: "{{ php_max_input_time }}" }
    - { section: "PHP", option: "memory_limit", value: "{{ php_memory_limit }}" }
    - { section: "PHP", option: "post_max_size", value: "{{ php_post_max_size }}" }
    - { section: "PHP", option: "upload_max_filesize", value: "{{ php_upload_max_filesize }}" }
    - { section: "PHP", option: "expose_php", value: "{{ php_expose_php }}" }          # security: do not expose php
    - { section: "PHP", option: "display_errors", value: "{{ php_display_errors }}" }  # security: do not show errors onsite
    - { section: "PHP", option: "display_startup_errors", value: "Off" }               # security: do not show errors onsite
    - { section: "Session", option: "session.use_strict_mode", value: "1" }            # security: prevents session fixation attacks
    - { section: "Session", option: "session.gc_maxlifetime", value: "{{ php_session_maxlifetime }}" }    # max session lifetime
    - { section: "dba", option: "opcache.enable", value: "1" }                    # performance: enable opcache ...
    - { section: "dba", option: "opcache.enable_cli", value: "0" }                # ... but disable opcache for commandline
    - { section: "dba", option: "opcache.memory_consumption", value: "64" }
    - { section: "dba", option: "opcache.interned_strings_buffer", value: "4" }
    - { section: "dba", option: "opcache.max_accelerated_files", value: "2000" }
    - { section: "dba", option: "opcache.max_wasted_percentage", value: "5" }
    - { section: "dba", option: "opcache.use_cwd", value: "1" }
    - { section: "dba", option: "opcache.validate_timestamps", value: "1" }
    - { section: "dba", option: "opcache.revalidate_freq", value: "2" }
    - { section: "dba", option: "opcache.revalidate_path", value: "0" }
    - { section: "dba", option: "opcache.error_log", value: '"{{ php_log_path }}/opcache_cli.log"' }
    - { section: "dba", option: "opcache.log_verbosity_level", value: "1" }
    - { section: "mail function", option: "mail.log", value: '"{{ php_log_path }}/mail_cli.log"' }
