#!/bin/bash -x

# run some prerequisite tests for couchdb, see: https://docs.couchdb.org/en/stable/install/troubleshooting.html

echo "checking erlang version (return major version) ..."
erl -noshell -eval 'io:put_chars(erlang:system_info(otp_release)).' -s erlang halt
echo

echo "Checking erlang crypto support (output 'yay_crypto' if enabled) ..."
erl -noshell -eval 'case application:load(crypto) of ok -> io:put_chars("yay_crypto\n") ; _ -> exit(no_crypto) end.' -s init stop
echo
